print("Hi there!😃")
name = input("What is your name?: ").capitalize()
print(f"That is a beautiful name, {name}")
colour = input("Tell me what is your favourite colour?: ").capitalize()
animal = input("What is your favourite animal? ").capitalize()
print(f"Hmm, {colour} is a nice one and a {animal} is a beautiful creature.\nIt was nice knowing you,{name}\nI hope to see you soon,Bye")